# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qrcode.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from googleapiclient import discovery
from googleapiclient import errors
from httplib2 import Http
from oauth2client import file, client, tools
import base64
from bs4 import BeautifulSoup
import re
import time
import dateutil.parser as parser
from datetime import datetime
import datetime
import csv
import time
import requests


class Ui_qrcodepage(object):
        
        def Home2(self):
                from Home import Ui_Home
                self.window6 = QtWidgets.QMainWindow()
                self.ui = Ui_Home()
                self.ui.setupUi(self.window6)
                self.window6.show()
        def setupUi(self, qrcodepage):
                qrcodepage.setObjectName("qrcodepage")
                qrcodepage.resize(800, 485)
                qrcodepage.setStyleSheet("background:#F5DEB3")
                self.centralwidget = QtWidgets.QWidget(qrcodepage)
                self.centralwidget.setObjectName("centralwidget")
                self.frame = QtWidgets.QFrame(self.centralwidget)
                self.frame.setGeometry(QtCore.QRect(200, 100, 381, 331))
                self.frame.setStyleSheet("QFrame\n"
"{\n"
"    background:#333\n"
"}")
                self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame.setObjectName("frame")
                self.label = QtWidgets.QLabel(self.frame)
                self.label.setGeometry(QtCore.QRect(95, 20, 251, 71))
                self.label.setStyleSheet("*{\n"
"    font-family:century gothic;\n"
"    font-size:27px;\n"
"    color:white;\n"
"\n"
"}")
                self.label.setObjectName("label")
                self.toolButton_2 = QtWidgets.QToolButton(self.frame)
                self.toolButton_2.setGeometry(QtCore.QRect(90, 90, 211, 211))
                self.toolButton_2.setStyleSheet("")
                icon = QtGui.QIcon()
                icon.addPixmap(QtGui.QPixmap("qrcode.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                self.toolButton_2.setIcon(icon)
                self.toolButton_2.setIconSize(QtCore.QSize(400, 400))
                self.toolButton_2.setAutoRepeat(False)
                self.toolButton_2.setAutoExclusive(False)
                self.toolButton_2.setObjectName("toolButton_2")
                self.toolButton = QtWidgets.QToolButton(self.centralwidget)
                self.toolButton.setGeometry(QtCore.QRect(340, 10, 121, 121))
                self.toolButton.setStyleSheet("#toolButton{\n"
"background:red;\n"
"border-radius:60px;\n"
"}")
                icon1 = QtGui.QIcon()
                icon1.addPixmap(QtGui.QPixmap("kisspng-washing-machine-laundry-scalable-vector-graphics-c-a-washing-machine-5a6e0ac989c6a7.9257319415171611615644.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                self.toolButton.setIcon(icon1)
                self.toolButton.setIconSize(QtCore.QSize(100, 90))
                self.toolButton.setAutoRepeat(False)
                self.toolButton.setAutoExclusive(False)
                self.toolButton.setObjectName("toolButton")
                self.pushButton2 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton2.setGeometry(QtCore.QRect(610, 370, 61, 61))
                self.pushButton2.setStyleSheet("#pushButton2{\n"
"background:white;\n"
"font-size:24px;\n"
"color:white;\n"
"border-radius:15px;\n"
"}\n"
"#pushButtonHover2{\n"
"background:white;\n"
"font-size:24px;\n"
"color:black;\n"
"border-radius:15px;\n"
"}")
                self.pushButton2.setText("")
                icon2 = QtGui.QIcon()
                icon2.addPixmap(QtGui.QPixmap("home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                self.pushButton2.setIcon(icon2)
                self.pushButton2.setIconSize(QtCore.QSize(50, 50))
                self.pushButton2.setObjectName("pushButton2")
                self.pushButton2.clicked.connect(self.Home2)
                self.pushButton2.clicked.connect(qrcodepage.close)
                qrcodepage.setCentralWidget(self.centralwidget)
                self.menubar = QtWidgets.QMenuBar(qrcodepage)
                self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
                self.menubar.setObjectName("menubar")
                qrcodepage.setMenuBar(self.menubar)
                self.statusbar = QtWidgets.QStatusBar(qrcodepage)
                self.statusbar.setObjectName("statusbar")
                qrcodepage.setStatusBar(self.statusbar)

                self.retranslateUi(qrcodepage)
                QtCore.QMetaObject.connectSlotsByName(qrcodepage)

        def retranslateUi(self, qrcodepage):
                _translate = QtCore.QCoreApplication.translate
                qrcodepage.setWindowTitle(_translate("qrcodepage", "qrcodepage"))
                self.label.setText(_translate("qrcodepage", "QR Code Payment"))
                self.toolButton_2.setText(_translate("qrcodepage", "..."))
                self.toolButton.setText(_translate("qrcodepage", "..."))
        
import PyQt5


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    qrcodepage = QtWidgets.QMainWindow()
    ui = Ui_qrcodepage()
    ui.setupUi(qrcodepage)
    qrcodepage.show()
    sys.exit(app.exec_())
