# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Register.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_registerpage(object):
        def Home1(self):
                from Home import Ui_Home
                self.window5 = QtWidgets.QMainWindow()
                self.ui = Ui_Home()
                self.ui.setupUi(self.window5)
                self.window5.show()

        def setupUi(self, registerpage):
                registerpage.setObjectName("registerpage")
                registerpage.resize(800, 600)
                registerpage.setStyleSheet("background:#F5DEB3")
                self.centralwidget = QtWidgets.QWidget(registerpage)
                self.centralwidget.setObjectName("centralwidget")
                self.frame = QtWidgets.QFrame(self.centralwidget)
                self.frame.setGeometry(QtCore.QRect(190, 130, 401, 421))
                self.frame.setStyleSheet("QFrame\n"
"{\n"
"    background:#333\n"
"}")
                self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame.setObjectName("frame")
                self.label = QtWidgets.QLabel(self.frame)
                self.label.setGeometry(QtCore.QRect(160, 50, 151, 61))
                self.label.setStyleSheet("*{\n"
"    font-family:century gothic;\n"
"    font-size:24px;\n"
"    color:white;\n"
"\n"
"}")
                self.label.setObjectName("label")
                self.lineEdit = QtWidgets.QLineEdit(self.frame)
                self.lineEdit.setGeometry(QtCore.QRect(40, 120, 311, 51))
                self.lineEdit.setStyleSheet("QLineEdit{\n"
"background:transparent;\n"
"border:none;\n"
"font-size:20px;\n"
"color:#717072;\n"
"border-bottom:1px solid #717072;\n"
"}")
                self.lineEdit.setText("")
                self.lineEdit.setMaxLength(32768)
                self.lineEdit.setFrame(True)
                self.lineEdit.setCursorPosition(0)
                self.lineEdit.setObjectName("lineEdit")
                self.res2 = QtWidgets.QPushButton(self.frame)
                self.res2.setGeometry(QtCore.QRect(50, 360, 311, 41))
                self.res2.setStyleSheet("#res2{\n"
"background:red;\n"
"font-size:24px;\n"
"color:white;\n"
"border-radius:15px;\n"
"}\n"
"#pushButtonHover{\n"
"background:white;\n"
"font-size:24px;\n"
"color:black;\n"
"border-radius:15px;\n"
"}")
                self.res2.setObjectName("res2")
                self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
                self.lineEdit_2.setGeometry(QtCore.QRect(40, 200, 311, 51))
                self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"background:transparent;\n"
"border:none;\n"
"font-size:20px;\n"
"color:#717072;\n"
"border-bottom:1px solid #717072;\n"
"}")
                self.lineEdit_2.setText("")
                self.lineEdit_2.setMaxLength(32768)
                self.lineEdit_2.setFrame(True)
                self.lineEdit_2.setCursorPosition(0)
                self.lineEdit_2.setObjectName("lineEdit_2")
                self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
                self.lineEdit_3.setGeometry(QtCore.QRect(40, 280, 311, 51))
                self.lineEdit_3.setStyleSheet("QLineEdit{\n"
"background:transparent;\n"
"border:none;\n"
"font-size:20px;\n"
"color:#717072;\n"
"border-bottom:1px solid #717072;\n"
"}")
                self.lineEdit_3.setText("")
                self.lineEdit_3.setMaxLength(32768)
                self.lineEdit_3.setFrame(True)
                self.lineEdit_3.setCursorPosition(0)
                self.lineEdit_3.setObjectName("lineEdit_3")
                self.toolButton = QtWidgets.QToolButton(self.centralwidget)
                self.toolButton.setGeometry(QtCore.QRect(330, 50, 131, 131))
                self.toolButton.setStyleSheet("#toolButton{\n"
"background:red;\n"
"border-radius:60px;\n"
"}")
                icon = QtGui.QIcon()
                icon.addPixmap(QtGui.QPixmap("register.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                self.toolButton.setIcon(icon)
                self.toolButton.setIconSize(QtCore.QSize(80, 80))
                self.toolButton.setAutoRepeat(False)
                self.toolButton.setAutoExclusive(False)
                self.toolButton.setObjectName("toolButton")
                self.pushButton2 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton2.setGeometry(QtCore.QRect(690, 490, 61, 61))
                self.pushButton2.setStyleSheet("#pushButton2{\n"
"background:white;\n"
"font-size:24px;\n"
"color:white;\n"
"border-radius:15px;\n"
"}\n"
"#pushButtonHover2{\n"
"background:white;\n"
"font-size:24px;\n"
"color:black;\n"
"border-radius:15px;\n"
"}")
                self.pushButton2.setText("")
                icon1 = QtGui.QIcon()
                icon1.addPixmap(QtGui.QPixmap("home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                self.pushButton2.setIcon(icon1)
                self.pushButton2.setIconSize(QtCore.QSize(50, 50))
                self.pushButton2.setObjectName("pushButton2")
                self.pushButton2.clicked.connect(self.Home1)
                self.pushButton2.clicked.connect(registerpage.close)
                registerpage.setCentralWidget(self.centralwidget)
                self.menubar = QtWidgets.QMenuBar(registerpage)
                self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
                self.menubar.setObjectName("menubar")
                registerpage.setMenuBar(self.menubar)
                self.statusbar = QtWidgets.QStatusBar(registerpage)
                self.statusbar.setObjectName("statusbar")
                registerpage.setStatusBar(self.statusbar)

                self.retranslateUi(registerpage)
                QtCore.QMetaObject.connectSlotsByName(registerpage)

        def retranslateUi(self, registerpage):
                _translate = QtCore.QCoreApplication.translate
                registerpage.setWindowTitle(_translate("registerpage", "registerpage"))
                self.label.setText(_translate("registerpage", "Register"))
                self.lineEdit.setPlaceholderText(_translate("registerpage", "USERNAME"))
                self.res2.setText(_translate("registerpage", "Register"))
                self.lineEdit_2.setPlaceholderText(_translate("registerpage", "PASSWORD"))
                self.lineEdit_3.setPlaceholderText(_translate("registerpage", "ROOM NUMBER"))
                self.toolButton.setText(_translate("registerpage", "..."))
import PyQt5


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    registerpage = QtWidgets.QMainWindow()
    ui = Ui_registerpage()
    ui.setupUi(registerpage)
    registerpage.show()
    sys.exit(app.exec_())
